# Generated by Django 3.1 on 2020-08-14 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0002_auto_20200814_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('food_price', models.PositiveIntegerField()),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=30)),
                ('restaurant_address', models.CharField(max_length=30)),
                ('restaurant_category', models.CharField(choices=[('Irani', 'Irani'), ('Italian', 'Italian'), ('FastFood', 'FastFood')], default='Irani', max_length=30)),
                ('restaurant_phone_number', models.CharField(max_length=30)),
                ('restaurant_bank_account_number', models.CharField(max_length=30)),
                ('restaurant_credit', models.PositiveIntegerField()),
                ('restaurant_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.restaurantuser')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_many', models.PositiveIntegerField(default=1)),
                ('order_number', models.PositiveIntegerField()),
                ('order_price', models.PositiveIntegerField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_received', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_app.restaurantuser')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.food')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.restaurant'),
        ),
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.restaurantuser')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.food')),
            ],
        ),
    ]
