# Generated by Django 3.1 on 2020-08-15 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20200814_0028'),
        ('manager', '0002_auto_20200815_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_app.restaurantuser'),
        ),
        migrations.AlterField(
            model_name='favoritelist',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.food'),
        ),
        migrations.AlterField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_app.restaurantuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.food'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='user_app.restaurantuser'),
        ),
    ]
